import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';
import { config } from '../config/config';
import { IPrediction } from '../models/Prediction';
import { IImage } from '../models/Image';
import { IExplanation } from '../models/Explanation';
import { IModel } from '../models/Model';

if (!fs.existsSync(config.reportsDir)) {
  fs.mkdirSync(config.reportsDir, { recursive: true });
}

export interface GenerateReportParams {
  prediction: IPrediction;
  image: IImage;
  explanation?: IExplanation | null;
  model?: IModel | null;
  reviewerName?: string;
  generatedByName: string;
}

export class PDFService {
  public static async generateReport(params: GenerateReportParams): Promise<{ filePath: string; fileName: string }> {
    const { prediction, image, explanation, model, reviewerName, generatedByName } = params;
    const fileName = `Report-${prediction.analysisId}.pdf`;
    const filePath = path.join(config.reportsDir, fileName);

    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 40, size: 'A4' });
      const stream = fs.createWriteStream(filePath);

      doc.pipe(stream);

      // --- Header with Medical Theme ---
      doc.rect(40, 40, doc.page.width - 80, 60).fill('#0f172a');
      doc.fillColor('#10b981').fontSize(18).font('Helvetica-Bold').text('COLOAI-POLYP DIAGNOSTIC REPORT', 55, 52);
      doc.fillColor('#94a3b8').fontSize(9).font('Helvetica').text('Explainable Colorectal Polyp Classification & Decision Support System', 55, 75);

      // --- Metadata Grid ---
      doc.fillColor('#0f172a').fontSize(12).font('Helvetica-Bold').text('ANALYSIS SUMMARY', 40, 115);
      doc.moveTo(40, 130).lineTo(doc.page.width - 40, 130).stroke('#cbd5e1');

      doc.fontSize(10).font('Helvetica-Bold').fillColor('#334155');
      doc.text('Analysis ID:', 40, 140);
      doc.font('Helvetica').fillColor('#0f172a').text(prediction.analysisId, 130, 140);

      doc.font('Helvetica-Bold').fillColor('#334155').text('Timestamp:', 40, 158);
      doc.font('Helvetica').fillColor('#0f172a').text(new Date(prediction.createdAt).toLocaleString(), 130, 158);

      doc.font('Helvetica-Bold').fillColor('#334155').text('Generated By:', 40, 176);
      doc.font('Helvetica').fillColor('#0f172a').text(generatedByName, 130, 176);

      doc.font('Helvetica-Bold').fillColor('#334155').text('Model Version:', 320, 140);
      doc.font('Helvetica').fillColor('#0f172a').text(`${model?.name || 'Deep Hybrid Architecture'} (${model?.version || 'v1.0.0'})`, 420, 140);

      doc.font('Helvetica-Bold').fillColor('#334155').text('Architecture:', 320, 158);
      doc.font('Helvetica').fillColor('#0f172a').text(`${model?.backbone || 'Deep Vision Backbone'} / ${model?.classifier || 'Ensemble Classifier'}`, 420, 158);

      doc.font('Helvetica-Bold').fillColor('#334155').text('Review Status:', 320, 176);
      const statusColor = prediction.reviewStatus === 'REVIEWED' ? '#059669' : prediction.reviewStatus === 'REQUIRES_FURTHER_REVIEW' ? '#d97706' : '#64748b';
      doc.font('Helvetica-Bold').fillColor(statusColor).text(prediction.reviewStatus, 420, 176);

      // --- Prediction Badge & Probabilities ---
      doc.rect(40, 205, doc.page.width - 80, 50).fill('#f8fafc');
      doc.stroke('#e2e8f0');

      doc.fillColor('#0f172a').fontSize(11).font('Helvetica-Bold').text('PREDICTED CLASSIFICATION:', 55, 218);
      doc.fillColor('#059669').fontSize(14).text(`${prediction.predictedClass}`, 240, 216);
      doc.fillColor('#475569').fontSize(11).text(`(Confidence: ${(prediction.confidence * 100).toFixed(1)}%)`, 420, 218);

      // --- Colonoscopy Image Display ---
      doc.fillColor('#0f172a').fontSize(11).font('Helvetica-Bold').text('COLONOSCOPY IMAGE', 40, 275);
      doc.moveTo(40, 290).lineTo(280, 290).stroke('#cbd5e1');

      const imagePath = path.isAbsolute(image.storageKey)
        ? image.storageKey
        : path.join(config.uploadDir, path.basename(image.storageKey));

      let imageRendered = false;
      if (fs.existsSync(imagePath)) {
        try {
          doc.image(imagePath, 40, 300, { fit: [230, 160], align: 'center' });
          imageRendered = true;
        } catch (e) {
          console.warn('[PDFService] Could not embed image into PDF:', e);
        }
      }

      if (!imageRendered) {
        doc.rect(40, 300, 230, 160).fill('#f1f5f9');
        doc.fillColor('#64748b').fontSize(10).text('Colonoscopy Image Available in System', 60, 370);
      }

      // --- Class Probability Distribution ---
      doc.fillColor('#0f172a').fontSize(11).font('Helvetica-Bold').text('CLASS PROBABILITY DISTRIBUTION', 290, 275);
      doc.moveTo(290, 290).lineTo(doc.page.width - 40, 290).stroke('#cbd5e1');

      let probY = 305;
      for (const item of prediction.probabilities) {
        const pct = (item.probability * 100).toFixed(1);
        doc.fillColor('#334155').fontSize(9).font('Helvetica-Bold').text(item.className, 290, probY);
        doc.fillColor('#0f172a').font('Helvetica').text(`${pct}%`, 480, probY, { align: 'right', width: 60 });

        // Draw progress bar
        const barWidth = 230;
        const fillWidth = Math.max(2, (barWidth * item.probability));
        doc.rect(290, probY + 14, barWidth, 6).fill('#e2e8f0');
        doc.rect(290, probY + 14, fillWidth, 6).fill(item.className === prediction.predictedClass ? '#10b981' : '#94a3b8');

        probY += 30;
      }

      // --- Explainable AI (SHAP Contributions) ---
      doc.fillColor('#0f172a').fontSize(11).font('Helvetica-Bold').text('EXPLAINABLE AI: TOP SHAP FEATURE CONTRIBUTIONS', 40, 480);
      doc.moveTo(40, 495).lineTo(doc.page.width - 40, 495).stroke('#cbd5e1');

      let featY = 505;
      const contributions = explanation?.featureContributions?.slice(0, 4) || [];
      if (contributions.length > 0) {
        for (const feat of contributions) {
          const isPositive = feat.contribution >= 0;
          const sign = isPositive ? '+' : '';
          const color = isPositive ? '#059669' : '#dc2626';

          doc.fillColor('#1e293b').fontSize(9).font('Helvetica-Bold').text(feat.name, 40, featY);
          doc.fillColor(color).font('Helvetica-Bold').text(`${sign}${feat.contribution.toFixed(3)}`, 480, featY, { align: 'right', width: 60 });

          if (feat.description) {
            doc.fillColor('#64748b').fontSize(8).font('Helvetica').text(feat.description, 40, featY + 12);
          }
          featY += 28;
        }
      } else {
        doc.fillColor('#64748b').fontSize(9).text('SHAP TreeExplainer generated standardized high-level visual feature representations.', 40, featY);
        featY += 30;
      }

      // --- Clinical Review Section ---
      doc.fillColor('#0f172a').fontSize(11).font('Helvetica-Bold').text('CLINICAL & RESEARCH REVIEW', 40, featY + 15);
      doc.moveTo(40, featY + 30).lineTo(doc.page.width - 40, featY + 30).stroke('#cbd5e1');

      const reviewBoxY = featY + 38;
      doc.rect(40, reviewBoxY, doc.page.width - 80, 50).fill('#f8fafc').stroke('#e2e8f0');

      doc.fillColor('#334155').fontSize(9).font('Helvetica-Bold').text(`Reviewer: ${reviewerName || 'Unassigned / Pending Review'}`, 50, reviewBoxY + 10);
      doc.text(`Reviewed At: ${prediction.reviewedAt ? new Date(prediction.reviewedAt).toLocaleString() : 'N/A'}`, 320, reviewBoxY + 10);

      doc.font('Helvetica').fillColor('#475569').text(
        `Notes: ${prediction.reviewNotes || 'No clinician review notes entered yet.'}`,
        50,
        reviewBoxY + 26,
        { width: doc.page.width - 100 }
      );

      // --- Research & Regulatory Disclaimer ---
      const footerY = doc.page.height - 70;
      doc.rect(40, footerY, doc.page.width - 80, 45).fill('#fee2e2');
      doc.fillColor('#991b1b').fontSize(8).font('Helvetica-Bold').text('IMPORTANT REGULATORY & CLINICAL NOTICE:', 50, footerY + 8);
      doc.fillColor('#7f1d1d').fontSize(7.5).font('Helvetica').text(
        'This output is generated by an experimental deep learning decision-support system (Deep Neural Embeddings + SHAP) intended exclusively for computer-aided research. It DOES NOT constitute definitive medical diagnosis and must not replace professional clinical evaluation by a certified gastroenterologist or pathologist.',
        50,
        footerY + 18,
        { width: doc.page.width - 100 }
      );

      doc.end();

      stream.on('finish', () => resolve({ filePath, fileName }));
      stream.on('error', (err) => reject(err));
    });
  }
}
