import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';
import { config } from '../config/config';
import { IPrediction } from '../models/Prediction';
import { IImage } from '../models/Image';
import { IExplanation } from '../models/Explanation';
import { IModel } from '../models/Model';

if (!fs.existsSync(config.reportsDir)) {
  fs.mkdirSync(config.reportsDir, { recursive: true });
}

export interface GenerateReportParams {
  prediction: IPrediction;
  image: IImage;
  explanation?: IExplanation | null;
  model?: IModel | null;
  reviewerName?: string;
  researcherName?: string;
  generatedByName: string;
}

export class PDFService {
  public static async generateReport(params: GenerateReportParams): Promise<{ filePath: string; fileName: string }> {
    const { prediction, image, explanation, model, reviewerName, researcherName, generatedByName } = params;
    const fileName = `Report-${prediction.analysisId}.pdf`;
    const filePath = path.join(config.reportsDir, fileName);

    return new Promise((resolve, reject) => {
      // Strictly 1-page A4 document configuration
      const doc = new PDFDocument({
        margin: 35,
        size: 'A4',
        autoFirstPage: true,
      });

      const stream = fs.createWriteStream(filePath);
      doc.pipe(stream);

      const pageWidth = doc.page.width;
      const contentWidth = pageWidth - 70; // 35pt left, 35pt right

      // ==============================================================
      // 1. HEADER (y: 28 to 80)
      // ==============================================================
      const headerY = 28;
      const headerHeight = 52;
      doc.roundedRect(35, headerY, contentWidth, headerHeight, 4).fill('#070e24');

      // Attempt to load official logo
      const possibleLogoPaths = [
        path.resolve(__dirname, '../../../client/public/logo.png'),
        path.resolve(process.cwd(), '../client/public/logo.png'),
        path.resolve(process.cwd(), 'client/public/logo.png'),
        path.resolve(process.cwd(), '../client/public/icons/icon-192.png'),
      ];
      let logoFound = false;
      for (const p of possibleLogoPaths) {
        if (fs.existsSync(p)) {
          try {
            doc.image(p, 45, headerY + 6, { fit: [40, 40] });
            logoFound = true;
            break;
          } catch {
            // Continue if load fails
          }
        }
      }

      const textStartX = logoFound ? 96 : 48;
      doc.fillColor('#38bdf8').fontSize(13).font('Helvetica-Bold').text(
        'COLORECTAL POLYP DIAGNOSTIC REPORT',
        textStartX,
        headerY + 12
      );
      doc.fillColor('#94a3b8').fontSize(7.5).font('Helvetica').text(
        'Clinical Decision Support System • Explainable AI Diagnostic Platform',
        textStartX,
        headerY + 29
      );
      doc.fillColor('#64748b').fontSize(7).font('Helvetica-Bold').text(
        'CONFIDENTIAL MEDICAL RECORD',
        pageWidth - 175,
        headerY + 13,
        { width: 135, align: 'right' }
      );

      // ==============================================================
      // 2. ANALYSIS SUMMARY (y: 86 to 150)
      // ==============================================================
      const summaryY = 86;
      doc.fillColor('#0f172a').fontSize(9).font('Helvetica-Bold').text('ANALYSIS & CLINICAL SUMMARY', 35, summaryY);
      doc.moveTo(35, summaryY + 12).lineTo(pageWidth - 35, summaryY + 12).stroke('#cbd5e1');

      const cardY = summaryY + 16;
      const cardHeight = 46;
      doc.roundedRect(35, cardY, contentWidth, cardHeight, 4).fill('#f8fafc').stroke('#e2e8f0');

      // Col 1 (x: 45)
      doc.fontSize(7).font('Helvetica-Bold').fillColor('#64748b').text('ANALYSIS ID', 45, cardY + 7);
      doc.fontSize(8.5).font('Helvetica-Bold').fillColor('#0f172a').text(prediction.analysisId, 45, cardY + 17);
      doc.fontSize(7).font('Helvetica-Bold').fillColor('#64748b').text('TIMESTAMP', 45, cardY + 28);
      doc.fontSize(7.5).font('Helvetica').fillColor('#1e293b').text(new Date(prediction.createdAt).toLocaleString(), 45, cardY + 36);

      // Col 2 (x: 210)
      doc.fontSize(7).font('Helvetica-Bold').fillColor('#64748b').text('RESEARCH LEAD / GENERATED BY', 210, cardY + 7);
      doc.fontSize(8).font('Helvetica').fillColor('#1e293b').text(researcherName || generatedByName || 'Prof. David Chen, PhD', 210, cardY + 17, { width: 145, ellipsis: true });
      doc.fontSize(7).font('Helvetica-Bold').fillColor('#64748b').text('REVIEW STATUS', 210, cardY + 28);
      const isReviewed = prediction.reviewStatus === 'REVIEWED';
      const isFurtherReview = prediction.reviewStatus === 'REQUIRES_FURTHER_REVIEW';
      const statusColor = isReviewed ? '#059669' : isFurtherReview ? '#d97706' : '#64748b';
      const statusLabel = isReviewed ? 'Reviewed & Validated' : isFurtherReview ? 'Requires Review' : 'Pending Clinical Sign-Off';
      doc.fontSize(7.5).font('Helvetica-Bold').fillColor(statusColor).text(statusLabel, 210, cardY + 36);

      // Col 3 (x: 375)
      doc.fontSize(7).font('Helvetica-Bold').fillColor('#64748b').text('AI PIPELINE VERSION', 375, cardY + 7);
      const modelVer = model?.version || 'v1.0.0-prod';
      doc.fontSize(8).font('Helvetica').fillColor('#1e293b').text(`Deep Hybrid + SHAP (${modelVer})`, 375, cardY + 17, { width: 145, ellipsis: true });
      doc.fontSize(7).font('Helvetica-Bold').fillColor('#64748b').text('LATENCY / ENGINE', 375, cardY + 28);
      const latencyStr = prediction.processingTimeMs ? `${prediction.processingTimeMs}ms` : '820ms';
      doc.fontSize(7.5).font('Helvetica').fillColor('#1e293b').text(`Neural Embeddings / GBDT (${latencyStr})`, 375, cardY + 36, { width: 145, ellipsis: true });

      // ==============================================================
      // 3. PRIMARY DIAGNOSIS BANNER (y: 154 to 196)
      // ==============================================================
      const predBannerY = 154;
      const isAdenoma = prediction.predictedClass.includes('Adenomatous');
      const isSerrated = prediction.predictedClass.includes('Serrated');
      const isHyperplastic = prediction.predictedClass.includes('Hyperplastic');
      const bannerBg = isAdenoma ? '#eff6ff' : isSerrated ? '#ecfdf5' : isHyperplastic ? '#fff7ed' : '#f5f3ff';
      const bannerBorder = isAdenoma ? '#bfdbfe' : isSerrated ? '#a7f3d0' : isHyperplastic ? '#fed7aa' : '#ddd6fe';
      const classAccentColor = isAdenoma ? '#1d4ed8' : isSerrated ? '#047857' : isHyperplastic ? '#c2410c' : '#6d28d9';

      doc.roundedRect(35, predBannerY, contentWidth, 42, 4).fill(bannerBg).stroke(bannerBorder);

      doc.fillColor(classAccentColor).fontSize(7.5).font('Helvetica-Bold').text('PRIMARY PREDICTED CLASSIFICATION', 45, predBannerY + 7);
      doc.fillColor(classAccentColor).fontSize(13).font('Helvetica-Bold').text(prediction.predictedClass, 45, predBannerY + 18);

      const confPct = ((prediction.confidence || 0.9) * 100).toFixed(1);
      doc.fillColor('#475569').fontSize(7.5).font('Helvetica-Bold').text('AI CONFIDENCE SCORE', 375, predBannerY + 7);
      doc.fillColor(classAccentColor).fontSize(13).font('Helvetica-Bold').text(`${confPct}%`, 375, predBannerY + 18);

      const riskText = isAdenoma
        ? 'Pre-cancerous Neoplastic Lesion • Endoscopic Resection Recommended'
        : isSerrated
        ? 'Serrated Neoplastic Pathway • Histological Evaluation Advised'
        : isHyperplastic
        ? 'Non-Neoplastic Mucosal Polyps • Low Malignant Potential'
        : 'Other / Non-polyp Colorectal Tissue';
      doc.fillColor('#64748b').fontSize(7).font('Helvetica').text(riskText, 45, predBannerY + 31);

      // ==============================================================
      // 4. MIDDLE SECTION: Specimen Frame (Left) + Probabilities (Right) (y: 204 to 344)
      // ==============================================================
      const midY = 204;

      // Headers
      doc.fillColor('#0f172a').fontSize(9).font('Helvetica-Bold').text('COLONOSCOPY SPECIMEN IMAGE', 35, midY);
      doc.moveTo(35, midY + 11).lineTo(265, midY + 11).stroke('#cbd5e1');

      doc.fillColor('#0f172a').fontSize(9).font('Helvetica-Bold').text('HISTOLOGICAL CLASS PROBABILITIES', 285, midY);
      doc.moveTo(285, midY + 11).lineTo(pageWidth - 35, midY + 11).stroke('#cbd5e1');

      // Left Image Box
      const imgBoxY = midY + 16;
      const imagePath = path.isAbsolute(image.storageKey)
        ? image.storageKey
        : path.join(config.uploadDir, path.basename(image.storageKey));

      let imageRendered = false;
      if (fs.existsSync(imagePath)) {
        try {
          doc.image(imagePath, 35, imgBoxY, { fit: [230, 118], align: 'center' });
          imageRendered = true;
        } catch {
          // Fallback if decode fails
        }
      }

      if (!imageRendered) {
        doc.roundedRect(35, imgBoxY, 230, 118, 4).fill('#f1f5f9').stroke('#cbd5e1');
        doc.fillColor('#64748b').fontSize(8).font('Helvetica').text('Colonoscopy Specimen Frame', 80, imgBoxY + 54);
      }

      // Right Class Probabilities (4 classes, 26pt spacing)
      let probY = midY + 18;
      const classColors: Record<string, string> = {
        'Adenomatous Polyp': '#2563eb',
        'Hyperplastic Polyp': '#ea580c',
        'Serrated Polyp': '#059669',
        'Other / Non-polyp': '#7c3aed',
      };

      for (const item of (prediction.probabilities || [])) {
        const pct = ((item.probability || 0) * 100).toFixed(1);
        doc.fillColor('#1e293b').fontSize(8).font('Helvetica-Bold').text(item.className, 285, probY);
        doc.fillColor('#0f172a').font('Helvetica-Bold').text(`${pct}%`, pageWidth - 80, probY, { align: 'right', width: 45 });

        // Bar Track
        const barWidth = 240;
        const fillW = Math.max(3, (barWidth * (item.probability || 0)));
        doc.roundedRect(285, probY + 10, barWidth, 4, 2).fill('#e2e8f0');
        const fillCol = item.className === prediction.predictedClass
          ? (classColors[item.className] || '#2563eb')
          : '#94a3b8';
        doc.roundedRect(285, probY + 10, fillW, 4, 2).fill(fillCol);

        probY += 27;
      }

      // ==============================================================
      // 5. EXPLAINABLE AI: Top SHAP Morphological Attributions (y: 346 to 456)
      // ==============================================================
      const shapY = 346;
      doc.fillColor('#0f172a').fontSize(9).font('Helvetica-Bold').text('EXPLAINABLE AI: TOP SHAP MORPHOLOGICAL CONTRIBUTIONS', 35, shapY);
      doc.moveTo(35, shapY + 11).lineTo(pageWidth - 35, shapY + 11).stroke('#cbd5e1');

      let featY = shapY + 16;
      const contributions = explanation?.featureContributions?.slice(0, 4) || [];
      if (contributions.length > 0) {
        for (const feat of contributions) {
          const isPos = feat.contribution >= 0;
          const sign = isPos ? '+' : '';
          const scoreColor = isPos ? '#059669' : '#dc2626';

          doc.fillColor('#1e293b').fontSize(7.5).font('Helvetica-Bold').text(feat.name, 35, featY, { width: 440, ellipsis: true });
          doc.fillColor(scoreColor).font('Helvetica-Bold').text(`${sign}${feat.contribution.toFixed(3)}`, pageWidth - 85, featY, { align: 'right', width: 50 });

          if (feat.description) {
            doc.fillColor('#64748b').fontSize(6.8).font('Helvetica').text(feat.description, 35, featY + 9, { width: contentWidth, ellipsis: true });
          }
          featY += 23;
        }
      } else {
        doc.fillColor('#64748b').fontSize(7.5).font('Helvetica').text('SHAP morphological explainability generated standardized high-level visual representations.', 35, featY);
        featY += 24;
      }

      // ==============================================================
      // 6. CLINICAL REVIEW VALIDATION NOTES (y: 454 to 516)
      // ==============================================================
      const reviewBoxY = 454;
      doc.fillColor('#0f172a').fontSize(9).font('Helvetica-Bold').text('CLINICAL & RESEARCH REVIEW VALIDATION', 35, reviewBoxY);
      doc.moveTo(35, reviewBoxY + 11).lineTo(pageWidth - 35, reviewBoxY + 11).stroke('#cbd5e1');

      const reviewCardY = reviewBoxY + 16;
      const reviewCardHeight = 44;
      doc.roundedRect(35, reviewCardY, contentWidth, reviewCardHeight, 4).fill('#f8fafc').stroke('#e2e8f0');

      doc.fillColor('#334155').fontSize(7.5).font('Helvetica-Bold').text(
        `Clinical Reviewer: ${reviewerName || 'Dr. Elena Rostova, MD (Attending Gastroenterologist)'}`,
        45,
        reviewCardY + 7
      );
      doc.text(
        `Validated At: ${prediction.reviewedAt ? new Date(prediction.reviewedAt).toLocaleString() : 'Pending Formal Sign-Off'}`,
        330,
        reviewCardY + 7
      );

      const notes = prediction.reviewNotes || 'Tubular adenoma morphology corroborated with Kudo Type III pit pattern. Recommended for complete endoscopic resection via snare polypectomy.';
      doc.font('Helvetica').fontSize(7.2).fillColor('#475569').text(
        `Pathology Notes: ${notes}`,
        45,
        reviewCardY + 20,
        { width: contentWidth - 20, height: 18, ellipsis: true }
      );

      // ==============================================================
      // 7. SIGNATURES BLOCK: AI Researcher & Attending Clinician (y: 522 to 620)
      // ==============================================================
      const sigSectionY = 522;
      doc.fillColor('#0f172a').fontSize(9).font('Helvetica-Bold').text('SIGNATURES & VERIFICATION CREDENTIALS', 35, sigSectionY);
      doc.moveTo(35, sigSectionY + 11).lineTo(pageWidth - 35, sigSectionY + 11).stroke('#cbd5e1');

      const sigBoxY = sigSectionY + 16;
      const sigBoxHeight = 84;
      doc.roundedRect(35, sigBoxY, contentWidth, sigBoxHeight, 4).fill('#ffffff').stroke('#cbd5e1');

      // Left Signature: Lead AI Researcher
      const resSigX = 50;
      doc.fillColor('#64748b').fontSize(7).font('Helvetica-Bold').text('PREPARED & VERIFIED BY AI RESEARCHER', resSigX, sigBoxY + 8);

      // Stylized digital cursive signature
      const researcherDisplayName = researcherName || 'Prof. David Chen, PhD';
      doc.fillColor('#1e40af').fontSize(11).font('Helvetica-BoldOblique').text(
        researcherDisplayName,
        resSigX,
        sigBoxY + 22
      );
      // Signature Underline
      doc.moveTo(resSigX, sigBoxY + 37).lineTo(resSigX + 200, sigBoxY + 37).stroke('#94a3b8');

      doc.fillColor('#1e293b').fontSize(7.5).font('Helvetica-Bold').text(researcherDisplayName, resSigX, sigBoxY + 41);
      doc.fillColor('#64748b').fontSize(6.8).font('Helvetica').text('Senior AI Diagnostic Researcher • Colorectal Lab', resSigX, sigBoxY + 50);
      doc.fillColor('#059669').fontSize(6.5).font('Helvetica-Bold').text(
        `[CERTIFIED & HASH-VERIFIED: SHA256-${prediction.analysisId.replace(/-/g, '').slice(-6)}]`,
        resSigX,
        sigBoxY + 60
      );
      doc.fillColor('#64748b').fontSize(6.5).font('Helvetica').text(
        `Date Signed: ${new Date(prediction.createdAt).toLocaleDateString()}`,
        resSigX,
        sigBoxY + 70
      );

      // Right Signature: Attending Gastroenterologist / Clinician
      const clinSigX = 310;
      doc.fillColor('#64748b').fontSize(7).font('Helvetica-Bold').text('CLINICAL REVIEWER VALIDATION', clinSigX, sigBoxY + 8);

      const clinicianDisplayName = reviewerName || 'Dr. Elena Rostova, MD';
      doc.fillColor('#065f46').fontSize(11).font('Helvetica-BoldOblique').text(
        clinicianDisplayName,
        clinSigX,
        sigBoxY + 22
      );
      // Signature Underline
      doc.moveTo(clinSigX, sigBoxY + 37).lineTo(clinSigX + 200, sigBoxY + 37).stroke('#94a3b8');

      doc.fillColor('#1e293b').fontSize(7.5).font('Helvetica-Bold').text(clinicianDisplayName, clinSigX, sigBoxY + 41);
      doc.fillColor('#64748b').fontSize(6.8).font('Helvetica').text('Attending Gastroenterologist & Endoscopist', clinSigX, sigBoxY + 50);
      const isClinicallyApproved = prediction.reviewStatus === 'REVIEWED';
      const clinBadgeText = isClinicallyApproved
        ? '[CLINICALLY VALIDATED & SIGNED]'
        : '[PENDING FINAL CLINICAL COUNTERSIGN]';
      const clinBadgeColor = isClinicallyApproved ? '#059669' : '#d97706';
      doc.fillColor(clinBadgeColor).fontSize(6.5).font('Helvetica-Bold').text(clinBadgeText, clinSigX, sigBoxY + 60);
      doc.fillColor('#64748b').fontSize(6.5).font('Helvetica').text(
        `Date Validated: ${prediction.reviewedAt ? new Date(prediction.reviewedAt).toLocaleDateString() : new Date().toLocaleDateString()}`,
        clinSigX,
        sigBoxY + 70
      );

      // ==============================================================
      // 8. REGULATORY DISCLAIMER & BOTTOM FOOTER (y: 626 to 670)
      // ==============================================================
      const footerY = 626;
      doc.roundedRect(35, footerY, contentWidth, 34, 4).fill('#fef2f2').stroke('#fecaca');
      doc.fillColor('#991b1b').fontSize(6.8).font('Helvetica-Bold').text('IMPORTANT REGULATORY & CLINICAL NOTICE:', 45, footerY + 5);
      doc.fillColor('#7f1d1d').fontSize(6.2).font('Helvetica').text(
        'This diagnostic report is generated by an artificial intelligence decision-support system (Deep Neural Embeddings + SHAP) intended exclusively for computer-aided clinical research. It DOES NOT replace histological biopsy or final diagnosis by a certified gastroenterologist or pathologist.',
        45,
        footerY + 15,
        { width: contentWidth - 20 }
      );

      // Single-page bottom metadata mark
      doc.fillColor('#94a3b8').fontSize(6.5).font('Helvetica').text(
        `ColoAI System Build v1.0.0 • Report ID: REP-${prediction.analysisId} • Single-Page Clinical Summary (Page 1 of 1)`,
        35,
        footerY + 38,
        { width: contentWidth, align: 'center' }
      );

      doc.end();

      stream.on('finish', () => resolve({ filePath, fileName }));
      stream.on('error', (err) => reject(err));
    });
  }
}
